// Mocks generated by Mockito 5.4.6 from annotations
// in movies/test/helpers/test_helper_movie.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i13;
import 'dart:typed_data' as _i14;
import 'dart:ui' as _i11;

import 'package:bloc/bloc.dart' as _i12;
import 'package:core/module/core.dart' as _i6;
import 'package:dartz/dartz.dart' as _i4;
import 'package:flutter/material.dart' as _i10;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:movies/module/movies.dart' as _i3;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i2;
import 'package:tv_series/module/tv_series.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailTable_2 extends _i1.SmartFake
    implements _i3.MovieDetailTable {
  _FakeMovieDetailTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieRepository_4 extends _i1.SmartFake
    implements _i3.MovieRepository {
  _FakeMovieRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetNowPlayingMovies_5 extends _i1.SmartFake
    implements _i3.GetNowPlayingMovies {
  _FakeGetNowPlayingMovies_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularMovies_6 extends _i1.SmartFake
    implements _i3.GetPopularMovies {
  _FakeGetPopularMovies_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedMovies_7 extends _i1.SmartFake
    implements _i3.GetTopRatedMovies {
  _FakeGetTopRatedMovies_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUpComingMovies_8 extends _i1.SmartFake
    implements _i3.GetUpComingMovies {
  _FakeGetUpComingMovies_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieListState_9 extends _i1.SmartFake
    implements _i3.MovieListState {
  _FakeMovieListState_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieDetail_10 extends _i1.SmartFake
    implements _i3.GetMovieDetail {
  _FakeGetMovieDetail_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieRecommendations_11 extends _i1.SmartFake
    implements _i3.GetMovieRecommendations {
  _FakeGetMovieRecommendations_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatus_12 extends _i1.SmartFake
    implements _i3.GetWatchListStatus {
  _FakeGetWatchListStatus_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlist_13 extends _i1.SmartFake implements _i3.SaveWatchlist {
  _FakeSaveWatchlist_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlist_14 extends _i1.SmartFake
    implements _i3.RemoveWatchlist {
  _FakeRemoveWatchlist_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailState_15 extends _i1.SmartFake
    implements _i3.MovieDetailState {
  _FakeMovieDetailState_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeeMorePopularMovieState_16 extends _i1.SmartFake
    implements _i3.SeeMorePopularMovieState {
  _FakeSeeMorePopularMovieState_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchMovies_17 extends _i1.SmartFake implements _i3.SearchMovies {
  _FakeSearchMovies_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieSearchState_18 extends _i1.SmartFake
    implements _i3.MovieSearchState {
  _FakeMovieSearchState_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeeMoreTopRatedMovieState_19 extends _i1.SmartFake
    implements _i3.SeeMoreTopRatedMovieState {
  _FakeSeeMoreTopRatedMovieState_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeeMoreUpcomingMovieState_20 extends _i1.SmartFake
    implements _i3.SeeMoreUpcomingMovieState {
  _FakeSeeMoreUpcomingMovieState_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistMovies_21 extends _i1.SmartFake
    implements _i3.GetWatchlistMovies {
  _FakeGetWatchlistMovies_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistMovieState_22 extends _i1.SmartFake
    implements _i3.WatchlistMovieState {
  _FakeWatchlistMovieState_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_23 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_24 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i6.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i7.Future<_i2.Database>);

  @override
  _i7.Future<void> insertCacheTransaction(
    List<_i3.MovieTable>? movies,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransaction, [movies, category]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> insertCacheMovieDetail(_i3.MovieDetailTable? movieDetail) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheMovieDetail, [movieDetail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> getCachedMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMovieDetail, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> insertCacheTvDetail(_i8.TvSeriesDetailTable? tvDetail) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTvDetail, [tvDetail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> getCachedTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTvDetail, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheMovies, [category]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> insertWatchlistMovie(_i3.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistMovie, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlistMovie(_i3.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistMovie, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> insertCacheTransactionTvSeries(
    List<_i8.TvSeriesTable>? tvSeries,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransactionTvSeries, [
              tvSeries,
              category,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheTvSeries(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheTvSeries, [category]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> clearCacheTvSeries(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCacheTvSeries, [category]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> insertWatchlistTv(_i8.TvSeriesTable? tvTable) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistTv, [tvTable]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlistTv(_i8.TvSeriesTable? tvTable) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistTv, [tvTable]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i3.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.MovieModel>> getNowPlayingMovies({required int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, [], {#page: page}),
            returnValue: _i7.Future<List<_i3.MovieModel>>.value(
              <_i3.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i3.MovieModel>>);

  @override
  _i7.Future<List<_i3.MovieModel>> getPopularMovies({required int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, [], {#page: page}),
            returnValue: _i7.Future<List<_i3.MovieModel>>.value(
              <_i3.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i3.MovieModel>>);

  @override
  _i7.Future<List<_i3.MovieModel>> getTopRatedMovies({required int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, [], {#page: page}),
            returnValue: _i7.Future<List<_i3.MovieModel>>.value(
              <_i3.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i3.MovieModel>>);

  @override
  _i7.Future<List<_i3.MovieModel>> getUpComingMovies({required int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getUpComingMovies, [], {#page: page}),
            returnValue: _i7.Future<List<_i3.MovieModel>>.value(
              <_i3.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i3.MovieModel>>);

  @override
  _i7.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i7.Future<_i3.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_1(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.MovieDetailResponse>);

  @override
  _i7.Future<List<_i3.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i7.Future<List<_i3.MovieModel>>.value(
              <_i3.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i3.MovieModel>>);

  @override
  _i7.Future<List<_i3.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i7.Future<List<_i3.MovieModel>>.value(
              <_i3.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i3.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i3.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> cacheNowPlayingMovies(List<_i3.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheNowPlayingMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cachePopularMovies(List<_i3.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cachePopularMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheTopRatedMovies(List<_i3.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTopRatedMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheUpComingMovies(List<_i3.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUpComingMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheMovieDetail(_i3.MovieDetailTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#cacheMovieDetail, [movie]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.MovieTable>> getCachedNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedNowPlayingMovies, []),
            returnValue: _i7.Future<List<_i3.MovieTable>>.value(
              <_i3.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i3.MovieTable>>);

  @override
  _i7.Future<List<_i3.MovieTable>> getCachedPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPopularMovies, []),
            returnValue: _i7.Future<List<_i3.MovieTable>>.value(
              <_i3.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i3.MovieTable>>);

  @override
  _i7.Future<List<_i3.MovieTable>> getCachedTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTopRatedMovies, []),
            returnValue: _i7.Future<List<_i3.MovieTable>>.value(
              <_i3.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i3.MovieTable>>);

  @override
  _i7.Future<List<_i3.MovieTable>> getCachedUpComingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUpComingMovies, []),
            returnValue: _i7.Future<List<_i3.MovieTable>>.value(
              <_i3.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i3.MovieTable>>);

  @override
  _i7.Future<_i3.MovieDetailTable> getCachedMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMovieDetail, [id]),
            returnValue: _i7.Future<_i3.MovieDetailTable>.value(
              _FakeMovieDetailTable_2(
                this,
                Invocation.method(#getCachedMovieDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.MovieDetailTable>);

  @override
  _i7.Future<String> insertWatchlist(_i3.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> removeWatchlist(_i3.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i3.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i7.Future<_i3.MovieTable?>.value(),
          )
          as _i7.Future<_i3.MovieTable?>);

  @override
  _i7.Future<List<_i3.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i7.Future<List<_i3.MovieTable>>.value(
              <_i3.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i3.MovieTable>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i3.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> getNowPlayingMovies({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, [], {#page: page}),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#getNowPlayingMovies, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> getPopularMovies({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, [], {#page: page}),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#getPopularMovies, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> getTopRatedMovies({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, [], {#page: page}),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#getTopRatedMovies, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> getUpComingMovies({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUpComingMovies, [], {#page: page}),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#getUpComingMovies, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, _i3.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, _i3.MovieDetail>>.value(
                  _FakeEither_3<_i6.Failure, _i3.MovieDetail>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, _i3.MovieDetail>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> getMovieRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#getMovieRecommendations, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#searchMovies, [query]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> saveWatchlist(
    _i3.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [movie]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, String>>.value(
              _FakeEither_3<_i6.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, String>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> removeWatchlist(
    _i3.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, String>>.value(
              _FakeEither_3<_i6.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, String>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, bool>> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, bool>>.value(
              _FakeEither_3<_i6.Failure, bool>(
                this,
                Invocation.method(#isAddedToWatchlist, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, bool>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#getWatchlistMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i3.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, _i3.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, _i3.MovieDetail>>.value(
                  _FakeEither_3<_i6.Failure, _i3.MovieDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, _i3.MovieDetail>>);
}

/// A class which mocks [GetMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendations extends _i1.Mock
    implements _i3.GetMovieRecommendations {
  MockGetMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> execute(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i3.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, bool>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, bool>>.value(
              _FakeEither_3<_i6.Failure, bool>(
                this,
                Invocation.method(#execute, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, bool>>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i3.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> execute(_i3.MovieDetail? movie) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, String>>.value(
              _FakeEither_3<_i6.Failure, String>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i3.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> execute(_i3.MovieDetail? movie) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, String>>.value(
              _FakeEither_3<_i6.Failure, String>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, String>>);
}

/// A class which mocks [GetNowPlayingMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingMovies extends _i1.Mock
    implements _i3.GetNowPlayingMovies {
  MockGetNowPlayingMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> execute(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [page]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#execute, [page]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);
}

/// A class which mocks [GetTopRatedMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedMovies extends _i1.Mock implements _i3.GetTopRatedMovies {
  MockGetTopRatedMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> execute(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [page]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#execute, [page]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);
}

/// A class which mocks [SearchMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovies extends _i1.Mock implements _i3.SearchMovies {
  MockSearchMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> execute(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);
}

/// A class which mocks [GetPopularMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularMovies extends _i1.Mock implements _i3.GetPopularMovies {
  MockGetPopularMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> execute(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [page]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#execute, [page]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);
}

/// A class which mocks [GetUpComingMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUpComingMovies extends _i1.Mock implements _i3.GetUpComingMovies {
  MockGetUpComingMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get movieRepository =>
      (super.noSuchMethod(
            Invocation.getter(#movieRepository),
            returnValue: _FakeMovieRepository_4(
              this,
              Invocation.getter(#movieRepository),
            ),
          )
          as _i3.MovieRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> execute(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [page]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#execute, [page]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i3.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.Movie>>>);
}

/// A class which mocks [MovieListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListBloc extends _i1.Mock implements _i3.MovieListBloc {
  MockMovieListBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetNowPlayingMovies get getNowPlayingMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getNowPlayingMovies),
            returnValue: _FakeGetNowPlayingMovies_5(
              this,
              Invocation.getter(#getNowPlayingMovies),
            ),
          )
          as _i3.GetNowPlayingMovies);

  @override
  _i3.GetPopularMovies get getPopularMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularMovies),
            returnValue: _FakeGetPopularMovies_6(
              this,
              Invocation.getter(#getPopularMovies),
            ),
          )
          as _i3.GetPopularMovies);

  @override
  _i3.GetTopRatedMovies get getTopRatedMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedMovies),
            returnValue: _FakeGetTopRatedMovies_7(
              this,
              Invocation.getter(#getTopRatedMovies),
            ),
          )
          as _i3.GetTopRatedMovies);

  @override
  _i3.GetUpComingMovies get getUpComingMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getUpComingMovies),
            returnValue: _FakeGetUpComingMovies_8(
              this,
              Invocation.getter(#getUpComingMovies),
            ),
          )
          as _i3.GetUpComingMovies);

  @override
  _i3.MovieListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieListState_9(this, Invocation.getter(#state)),
          )
          as _i3.MovieListState);

  @override
  _i7.Stream<_i3.MovieListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.MovieListState>.empty(),
          )
          as _i7.Stream<_i3.MovieListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i10.ScrollController? controller, _i11.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.MovieListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.MovieListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.MovieListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.MovieListEvent>(
    _i12.EventHandler<E, _i3.MovieListState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.MovieListEvent, _i3.MovieListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.MovieListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i10.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i10.Route<dynamic>? route, _i10.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i10.Route<dynamic>? newRoute,
    _i10.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i10.Route<dynamic>? topRoute,
    _i10.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailBloc extends _i1.Mock implements _i3.MovieDetailBloc {
  MockMovieDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetMovieDetail get getMovieDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieDetail),
            returnValue: _FakeGetMovieDetail_10(
              this,
              Invocation.getter(#getMovieDetail),
            ),
          )
          as _i3.GetMovieDetail);

  @override
  _i3.GetMovieRecommendations get getMovieRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieRecommendations),
            returnValue: _FakeGetMovieRecommendations_11(
              this,
              Invocation.getter(#getMovieRecommendations),
            ),
          )
          as _i3.GetMovieRecommendations);

  @override
  _i3.GetWatchListStatus get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatus_12(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i3.GetWatchListStatus);

  @override
  _i3.SaveWatchlist get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlist_13(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i3.SaveWatchlist);

  @override
  _i3.RemoveWatchlist get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlist_14(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i3.RemoveWatchlist);

  @override
  _i3.MovieDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieDetailState_15(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.MovieDetailState);

  @override
  _i7.Stream<_i3.MovieDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.MovieDetailState>.empty(),
          )
          as _i7.Stream<_i3.MovieDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.MovieDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.MovieDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.MovieDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.MovieDetailEvent>(
    _i12.EventHandler<E, _i3.MovieDetailState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.MovieDetailEvent, _i3.MovieDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.MovieDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SeeMorePopularMovieBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeeMorePopularMovieBloc extends _i1.Mock
    implements _i3.SeeMorePopularMovieBloc {
  MockSeeMorePopularMovieBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetPopularMovies get getPopularMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularMovies),
            returnValue: _FakeGetPopularMovies_6(
              this,
              Invocation.getter(#getPopularMovies),
            ),
          )
          as _i3.GetPopularMovies);

  @override
  _i3.SeeMorePopularMovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSeeMorePopularMovieState_16(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.SeeMorePopularMovieState);

  @override
  _i7.Stream<_i3.SeeMorePopularMovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.SeeMorePopularMovieState>.empty(),
          )
          as _i7.Stream<_i3.SeeMorePopularMovieState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i10.ScrollController? controller, _i11.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.SeeMorePopularMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.SeeMorePopularMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.SeeMorePopularMovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.SeeMorePopularMovieEvent>(
    _i12.EventHandler<E, _i3.SeeMorePopularMovieState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.SeeMorePopularMovieEvent, _i3.SeeMorePopularMovieState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.SeeMorePopularMovieState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchBloc extends _i1.Mock implements _i3.MovieSearchBloc {
  MockMovieSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SearchMovies get searchMovies =>
      (super.noSuchMethod(
            Invocation.getter(#searchMovies),
            returnValue: _FakeSearchMovies_17(
              this,
              Invocation.getter(#searchMovies),
            ),
          )
          as _i3.SearchMovies);

  @override
  _i3.MovieSearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieSearchState_18(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.MovieSearchState);

  @override
  _i7.Stream<_i3.MovieSearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.MovieSearchState>.empty(),
          )
          as _i7.Stream<_i3.MovieSearchState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.MovieSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.MovieSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.MovieSearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.MovieSearchEvent>(
    _i12.EventHandler<E, _i3.MovieSearchState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.MovieSearchEvent, _i3.MovieSearchState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.MovieSearchState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SeeMoreTopRatedMovieBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeeMoreTopRatedMovieBloc extends _i1.Mock
    implements _i3.SeeMoreTopRatedMovieBloc {
  MockSeeMoreTopRatedMovieBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetTopRatedMovies get getTopRatedMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedMovies),
            returnValue: _FakeGetTopRatedMovies_7(
              this,
              Invocation.getter(#getTopRatedMovies),
            ),
          )
          as _i3.GetTopRatedMovies);

  @override
  _i3.SeeMoreTopRatedMovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSeeMoreTopRatedMovieState_19(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.SeeMoreTopRatedMovieState);

  @override
  _i7.Stream<_i3.SeeMoreTopRatedMovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.SeeMoreTopRatedMovieState>.empty(),
          )
          as _i7.Stream<_i3.SeeMoreTopRatedMovieState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i10.ScrollController? controller, _i11.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.SeeMoreTopRatedMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.SeeMoreTopRatedMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.SeeMoreTopRatedMovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.SeeMoreTopRatedMovieEvent>(
    _i12.EventHandler<E, _i3.SeeMoreTopRatedMovieState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<
      _i3.SeeMoreTopRatedMovieEvent,
      _i3.SeeMoreTopRatedMovieState
    >?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.SeeMoreTopRatedMovieState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SeeMoreUpcomingMovieBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeeMoreUpcomingMovieBloc extends _i1.Mock
    implements _i3.SeeMoreUpcomingMovieBloc {
  MockSeeMoreUpcomingMovieBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetUpComingMovies get getUpComingMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getUpComingMovies),
            returnValue: _FakeGetUpComingMovies_8(
              this,
              Invocation.getter(#getUpComingMovies),
            ),
          )
          as _i3.GetUpComingMovies);

  @override
  _i3.SeeMoreUpcomingMovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSeeMoreUpcomingMovieState_20(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.SeeMoreUpcomingMovieState);

  @override
  _i7.Stream<_i3.SeeMoreUpcomingMovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.SeeMoreUpcomingMovieState>.empty(),
          )
          as _i7.Stream<_i3.SeeMoreUpcomingMovieState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i10.ScrollController? controller, _i11.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.SeeMoreUpcomingMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.SeeMoreUpcomingMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.SeeMoreUpcomingMovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.SeeMoreUpcomingMovieEvent>(
    _i12.EventHandler<E, _i3.SeeMoreUpcomingMovieState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<
      _i3.SeeMoreUpcomingMovieEvent,
      _i3.SeeMoreUpcomingMovieState
    >?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.SeeMoreUpcomingMovieState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistMovieBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistMovieBloc extends _i1.Mock
    implements _i3.WatchlistMovieBloc {
  MockWatchlistMovieBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetWatchlistMovies get getWatchlistMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistMovies),
            returnValue: _FakeGetWatchlistMovies_21(
              this,
              Invocation.getter(#getWatchlistMovies),
            ),
          )
          as _i3.GetWatchlistMovies);

  @override
  _i3.WatchlistMovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWatchlistMovieState_22(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.WatchlistMovieState);

  @override
  _i7.Stream<_i3.WatchlistMovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.WatchlistMovieState>.empty(),
          )
          as _i7.Stream<_i3.WatchlistMovieState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.WatchlistMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.WatchlistMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.WatchlistMovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.WatchlistMovieEvent>(
    _i12.EventHandler<E, _i3.WatchlistMovieState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.WatchlistMovieEvent, _i3.WatchlistMovieState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.WatchlistMovieState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_23(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_23(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_23(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_23(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_23(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_23(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i14.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i7.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
          )
          as _i7.Future<_i14.Uint8List>);

  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i7.Future<_i5.StreamedResponse>.value(
              _FakeStreamedResponse_24(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
