// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/tv_series/on_the_air_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i11;

import 'package:ditonton_clean_architecture/common/state_enum.dart' as _i8;
import 'package:ditonton_clean_architecture/domain/entities/tv/tv_series.dart'
    as _i7;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_airing_today_tv.dart'
    as _i2;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_on_the_air_tv.dart'
    as _i3;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_popular_tv.dart'
    as _i4;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_top_rated_tv.dart'
    as _i5;
import 'package:ditonton_clean_architecture/presentation/provider/tv_series/tv_list_notifier.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAiringTodayTv_0 extends _i1.SmartFake
    implements _i2.GetAiringTodayTv {
  _FakeGetAiringTodayTv_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTv_1 extends _i1.SmartFake implements _i3.GetOnTheAirTv {
  _FakeGetOnTheAirTv_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTv_2 extends _i1.SmartFake implements _i4.GetPopularTv {
  _FakeGetPopularTv_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTv_3 extends _i1.SmartFake implements _i5.GetTopRatedTv {
  _FakeGetTopRatedTv_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvListNotifier extends _i1.Mock implements _i6.TvListNotifier {
  MockTvListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAiringTodayTv get getAiringTodayTv =>
      (super.noSuchMethod(
            Invocation.getter(#getAiringTodayTv),
            returnValue: _FakeGetAiringTodayTv_0(
              this,
              Invocation.getter(#getAiringTodayTv),
            ),
          )
          as _i2.GetAiringTodayTv);

  @override
  _i3.GetOnTheAirTv get getOnTheAirTv =>
      (super.noSuchMethod(
            Invocation.getter(#getOnTheAirTv),
            returnValue: _FakeGetOnTheAirTv_1(
              this,
              Invocation.getter(#getOnTheAirTv),
            ),
          )
          as _i3.GetOnTheAirTv);

  @override
  _i4.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_2(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i4.GetPopularTv);

  @override
  _i5.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_3(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i5.GetTopRatedTv);

  @override
  List<_i7.TvSeries> get airingTodayTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#airingTodayTvSeries),
            returnValue: <_i7.TvSeries>[],
          )
          as List<_i7.TvSeries>);

  @override
  List<_i7.TvSeries> get onTheAirTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#onTheAirTvSeries),
            returnValue: <_i7.TvSeries>[],
          )
          as List<_i7.TvSeries>);

  @override
  List<_i7.TvSeries> get popularTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#popularTvSeries),
            returnValue: <_i7.TvSeries>[],
          )
          as List<_i7.TvSeries>);

  @override
  List<_i7.TvSeries> get topRatedTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#topRatedTvSeries),
            returnValue: <_i7.TvSeries>[],
          )
          as List<_i7.TvSeries>);

  @override
  _i8.RequestState get airingTodayState =>
      (super.noSuchMethod(
            Invocation.getter(#airingTodayState),
            returnValue: _i8.RequestState.Empty,
          )
          as _i8.RequestState);

  @override
  _i8.RequestState get onTheAirState =>
      (super.noSuchMethod(
            Invocation.getter(#onTheAirState),
            returnValue: _i8.RequestState.Empty,
          )
          as _i8.RequestState);

  @override
  _i8.RequestState get popularTvState =>
      (super.noSuchMethod(
            Invocation.getter(#popularTvState),
            returnValue: _i8.RequestState.Empty,
          )
          as _i8.RequestState);

  @override
  _i8.RequestState get topRatedTvState =>
      (super.noSuchMethod(
            Invocation.getter(#topRatedTvState),
            returnValue: _i8.RequestState.Empty,
          )
          as _i8.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> fetchTvSeriesAiringToday() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesAiringToday, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> fetchTvSeriesOnTheAir() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesOnTheAir, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> fetchTvSeriesPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesPopularTv, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> fetchTvSeriesTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesTopRatedTv, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
