// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/tv_series/top_rated_tv_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:ditonton_clean_architecture/common/state_enum.dart' as _i6;
import 'package:ditonton_clean_architecture/domain/entities/tv/tv_series.dart'
    as _i7;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_top_rated_tv.dart'
    as _i2;
import 'package:ditonton_clean_architecture/presentation/provider/tv_series/top_rated_tv_notifier.dart'
    as _i5;
import 'package:flutter/cupertino.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:pull_to_refresh/pull_to_refresh.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTopRatedTv_0 extends _i1.SmartFake implements _i2.GetTopRatedTv {
  _FakeGetTopRatedTv_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshController_1 extends _i1.SmartFake
    implements _i3.RefreshController {
  _FakeRefreshController_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScrollController_2 extends _i1.SmartFake
    implements _i4.ScrollController {
  _FakeScrollController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TopRatedTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvNotifier extends _i1.Mock
    implements _i5.TopRatedTvNotifier {
  MockTopRatedTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_0(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i2.GetTopRatedTv);

  @override
  _i3.RefreshController get refreshC =>
      (super.noSuchMethod(
            Invocation.getter(#refreshC),
            returnValue: _FakeRefreshController_1(
              this,
              Invocation.getter(#refreshC),
            ),
          )
          as _i3.RefreshController);

  @override
  _i4.ScrollController get scrollController =>
      (super.noSuchMethod(
            Invocation.getter(#scrollController),
            returnValue: _FakeScrollController_2(
              this,
              Invocation.getter(#scrollController),
            ),
          )
          as _i4.ScrollController);

  @override
  _i6.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.RequestState.Empty,
          )
          as _i6.RequestState);

  @override
  List<_i7.TvSeries> get tvSeriesList =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeriesList),
            returnValue: <_i7.TvSeries>[],
          )
          as List<_i7.TvSeries>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get isFetching =>
      (super.noSuchMethod(Invocation.getter(#isFetching), returnValue: false)
          as bool);

  @override
  set refreshC(_i3.RefreshController? _refreshC) => super.noSuchMethod(
    Invocation.setter(#refreshC, _refreshC),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<void> loadMoreTvTopRated() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreTvTopRated, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> loadTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#loadTvSeries, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> onRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#onRefresh, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> fetchTvSeriesTopRated() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesTopRated, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
