// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/tv_series/top_rated_tv_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:bloc/bloc.dart' as _i7;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_top_rated_tv.dart'
    as _i2;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/see_more_top_rated/see_more_top_rated_tv_bloc.dart'
    as _i3;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTopRatedTv_0 extends _i1.SmartFake implements _i2.GetTopRatedTv {
  _FakeGetTopRatedTv_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeeMoreTopRatedTvState_1 extends _i1.SmartFake
    implements _i3.SeeMoreTopRatedTvState {
  _FakeSeeMoreTopRatedTvState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SeeMoreTopRatedTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeeMoreTopRatedTvBloc extends _i1.Mock
    implements _i3.SeeMoreTopRatedTvBloc {
  MockSeeMoreTopRatedTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_0(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i2.GetTopRatedTv);

  @override
  _i3.SeeMoreTopRatedTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSeeMoreTopRatedTvState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.SeeMoreTopRatedTvState);

  @override
  _i4.Stream<_i3.SeeMoreTopRatedTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i3.SeeMoreTopRatedTvState>.empty(),
          )
          as _i4.Stream<_i3.SeeMoreTopRatedTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i5.ScrollController? controller, _i6.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.SeeMoreTopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.SeeMoreTopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.SeeMoreTopRatedTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.SeeMoreTopRatedTvEvent>(
    _i7.EventHandler<E, _i3.SeeMoreTopRatedTvState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i3.SeeMoreTopRatedTvEvent, _i3.SeeMoreTopRatedTvState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onChange(_i7.Change<_i3.SeeMoreTopRatedTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
