// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/tv_series/tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_airing_today_tv.dart'
    as _i4;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_on_the_air_tv.dart'
    as _i6;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_popular_tv.dart'
    as _i8;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_top_rated_tv.dart'
    as _i10;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_list/airing_today/airing_today_tv_bloc.dart'
    as _i5;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_list/on_the_air/on_the_air_tv_bloc.dart'
    as _i7;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_list/popular/popular_tv_bloc.dart'
    as _i9;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_list/top_rated/top_rated_tv_bloc.dart'
    as _i11;
import 'package:ditonton_clean_architecture/presentation/pages/tv_series/tv_series_page.dart'
    as _i12;
import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i1;
import 'package:flutter_bloc/flutter_bloc.dart' as _i15;
import 'package:mockito/mockito.dart' as _i2;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeState_0<T extends _i1.StatefulWidget> extends _i2.SmartFake
    implements _i1.State<T> {
  _FakeState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i1.DiagnosticLevel? minLevel = _i1.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeStatefulElement_1 extends _i2.SmartFake
    implements _i1.StatefulElement {
  _FakeStatefulElement_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i1.DiagnosticLevel? minLevel = _i1.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i2.SmartFake
    implements _i1.DiagnosticsNode {
  _FakeDiagnosticsNode_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i1.DiagnosticLevel? minLevel = _i1.DiagnosticLevel.info,
  }) => super.toString();
}

class _FakeGetAiringTodayTv_3 extends _i2.SmartFake
    implements _i4.GetAiringTodayTv {
  _FakeGetAiringTodayTv_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiringTodayTvState_4 extends _i2.SmartFake
    implements _i5.AiringTodayTvState {
  _FakeAiringTodayTvState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTv_5 extends _i2.SmartFake implements _i6.GetOnTheAirTv {
  _FakeGetOnTheAirTv_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnTheAirTvState_6 extends _i2.SmartFake
    implements _i7.OnTheAirTvState {
  _FakeOnTheAirTvState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTv_7 extends _i2.SmartFake implements _i8.GetPopularTv {
  _FakeGetPopularTv_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTvState_8 extends _i2.SmartFake
    implements _i9.PopularTvState {
  _FakePopularTvState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTv_9 extends _i2.SmartFake implements _i10.GetTopRatedTv {
  _FakeGetTopRatedTv_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTvState_10 extends _i2.SmartFake
    implements _i11.TopRatedTvState {
  _FakeTopRatedTvState_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvSeriesPage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesPage extends _i2.Mock implements _i12.TvSeriesPage {
  MockTvSeriesPage() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i1.State<_i12.TvSeriesPage> createState() =>
      (super.noSuchMethod(
            Invocation.method(#createState, []),
            returnValue: _FakeState_0<_i12.TvSeriesPage>(
              this,
              Invocation.method(#createState, []),
            ),
          )
          as _i1.State<_i12.TvSeriesPage>);

  @override
  _i1.StatefulElement createElement() =>
      (super.noSuchMethod(
            Invocation.method(#createElement, []),
            returnValue: _FakeStatefulElement_1(
              this,
              Invocation.method(#createElement, []),
            ),
          )
          as _i1.StatefulElement);

  @override
  String toStringShort() =>
      (super.noSuchMethod(
            Invocation.method(#toStringShort, []),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#toStringShort, []),
            ),
          )
          as String);

  @override
  void debugFillProperties(_i3.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(#debugFillProperties, [properties]),
        returnValueForMissingStub: null,
      );

  @override
  String toStringShallow({
    String? joiner = ', ',
    _i1.DiagnosticLevel? minLevel = _i1.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toStringShallow, [], {
              #joiner: joiner,
              #minLevel: minLevel,
            }),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#toStringShallow, [], {
                #joiner: joiner,
                #minLevel: minLevel,
              }),
            ),
          )
          as String);

  @override
  String toStringDeep({
    String? prefixLineOne = '',
    String? prefixOtherLines,
    _i1.DiagnosticLevel? minLevel = _i1.DiagnosticLevel.debug,
    int? wrapWidth = 65,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toStringDeep, [], {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
              #wrapWidth: wrapWidth,
            }),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#toStringDeep, [], {
                #prefixLineOne: prefixLineOne,
                #prefixOtherLines: prefixOtherLines,
                #minLevel: minLevel,
                #wrapWidth: wrapWidth,
              }),
            ),
          )
          as String);

  @override
  _i1.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i3.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toDiagnosticsNode, [], {
              #name: name,
              #style: style,
            }),
            returnValue: _FakeDiagnosticsNode_2(
              this,
              Invocation.method(#toDiagnosticsNode, [], {
                #name: name,
                #style: style,
              }),
            ),
          )
          as _i1.DiagnosticsNode);

  @override
  List<_i1.DiagnosticsNode> debugDescribeChildren() =>
      (super.noSuchMethod(
            Invocation.method(#debugDescribeChildren, []),
            returnValue: <_i1.DiagnosticsNode>[],
          )
          as List<_i1.DiagnosticsNode>);

  @override
  String toString({_i1.DiagnosticLevel? minLevel = _i1.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [AiringTodayTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiringTodayTvBloc extends _i2.Mock implements _i5.AiringTodayTvBloc {
  MockAiringTodayTvBloc() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i4.GetAiringTodayTv get getAiringTodayTv =>
      (super.noSuchMethod(
            Invocation.getter(#getAiringTodayTv),
            returnValue: _FakeGetAiringTodayTv_3(
              this,
              Invocation.getter(#getAiringTodayTv),
            ),
          )
          as _i4.GetAiringTodayTv);

  @override
  _i5.AiringTodayTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAiringTodayTvState_4(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.AiringTodayTvState);

  @override
  _i14.Stream<_i5.AiringTodayTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i14.Stream<_i5.AiringTodayTvState>.empty(),
          )
          as _i14.Stream<_i5.AiringTodayTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i5.AiringTodayTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.AiringTodayTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.AiringTodayTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.AiringTodayTvEvent>(
    _i15.EventHandler<E, _i5.AiringTodayTvState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i5.AiringTodayTvEvent, _i5.AiringTodayTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i5.AiringTodayTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnTheAirTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvBloc extends _i2.Mock implements _i7.OnTheAirTvBloc {
  MockOnTheAirTvBloc() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i6.GetOnTheAirTv get getOnTheAirTv =>
      (super.noSuchMethod(
            Invocation.getter(#getOnTheAirTv),
            returnValue: _FakeGetOnTheAirTv_5(
              this,
              Invocation.getter(#getOnTheAirTv),
            ),
          )
          as _i6.GetOnTheAirTv);

  @override
  _i7.OnTheAirTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOnTheAirTvState_6(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.OnTheAirTvState);

  @override
  _i14.Stream<_i7.OnTheAirTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i14.Stream<_i7.OnTheAirTvState>.empty(),
          )
          as _i14.Stream<_i7.OnTheAirTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.OnTheAirTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.OnTheAirTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.OnTheAirTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.OnTheAirTvEvent>(
    _i15.EventHandler<E, _i7.OnTheAirTvState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i7.OnTheAirTvEvent, _i7.OnTheAirTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i7.OnTheAirTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvBloc extends _i2.Mock implements _i9.PopularTvBloc {
  MockPopularTvBloc() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i8.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_7(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i8.GetPopularTv);

  @override
  _i9.PopularTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularTvState_8(this, Invocation.getter(#state)),
          )
          as _i9.PopularTvState);

  @override
  _i14.Stream<_i9.PopularTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i14.Stream<_i9.PopularTvState>.empty(),
          )
          as _i14.Stream<_i9.PopularTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i9.PopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.PopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i9.PopularTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.PopularTvEvent>(
    _i15.EventHandler<E, _i9.PopularTvState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i9.PopularTvEvent, _i9.PopularTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i9.PopularTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvBloc extends _i2.Mock implements _i11.TopRatedTvBloc {
  MockTopRatedTvBloc() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i10.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_9(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i10.GetTopRatedTv);

  @override
  _i11.TopRatedTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedTvState_10(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i11.TopRatedTvState);

  @override
  _i14.Stream<_i11.TopRatedTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i14.Stream<_i11.TopRatedTvState>.empty(),
          )
          as _i14.Stream<_i11.TopRatedTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i11.TopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.TopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i11.TopRatedTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.TopRatedTvEvent>(
    _i15.EventHandler<E, _i11.TopRatedTvState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i11.TopRatedTvEvent, _i11.TopRatedTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i11.TopRatedTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
