// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/tv_series/tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:ditonton_clean_architecture/common/state_enum.dart' as _i11;
import 'package:ditonton_clean_architecture/domain/entities/tv/tv_series.dart'
    as _i10;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_airing_today_tv.dart'
    as _i4;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_on_the_air_tv.dart'
    as _i5;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_popular_tv.dart'
    as _i6;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_top_rated_tv.dart'
    as _i7;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/search_tv_series.dart'
    as _i8;
import 'package:ditonton_clean_architecture/presentation/provider/tv_series/tv_list_notifier.dart'
    as _i9;
import 'package:ditonton_clean_architecture/presentation/provider/tv_series/tv_search_notifier.dart'
    as _i15;
import 'package:flutter/cupertino.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:pull_to_refresh/pull_to_refresh.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRefreshController_0 extends _i1.SmartFake
    implements _i2.RefreshController {
  _FakeRefreshController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScrollController_1 extends _i1.SmartFake
    implements _i3.ScrollController {
  _FakeScrollController_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAiringTodayTv_2 extends _i1.SmartFake
    implements _i4.GetAiringTodayTv {
  _FakeGetAiringTodayTv_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTv_3 extends _i1.SmartFake implements _i5.GetOnTheAirTv {
  _FakeGetOnTheAirTv_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTv_4 extends _i1.SmartFake implements _i6.GetPopularTv {
  _FakeGetPopularTv_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTv_5 extends _i1.SmartFake implements _i7.GetTopRatedTv {
  _FakeGetTopRatedTv_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchTvSeries_6 extends _i1.SmartFake
    implements _i8.SearchTvSeries {
  _FakeSearchTvSeries_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvListNotifier extends _i1.Mock implements _i9.TvListNotifier {
  MockTvListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RefreshController get refreshC =>
      (super.noSuchMethod(
            Invocation.getter(#refreshC),
            returnValue: _FakeRefreshController_0(
              this,
              Invocation.getter(#refreshC),
            ),
          )
          as _i2.RefreshController);

  @override
  _i3.ScrollController get airingTodayController =>
      (super.noSuchMethod(
            Invocation.getter(#airingTodayController),
            returnValue: _FakeScrollController_1(
              this,
              Invocation.getter(#airingTodayController),
            ),
          )
          as _i3.ScrollController);

  @override
  _i3.ScrollController get onTheAirController =>
      (super.noSuchMethod(
            Invocation.getter(#onTheAirController),
            returnValue: _FakeScrollController_1(
              this,
              Invocation.getter(#onTheAirController),
            ),
          )
          as _i3.ScrollController);

  @override
  _i3.ScrollController get popularController =>
      (super.noSuchMethod(
            Invocation.getter(#popularController),
            returnValue: _FakeScrollController_1(
              this,
              Invocation.getter(#popularController),
            ),
          )
          as _i3.ScrollController);

  @override
  _i3.ScrollController get topRatedController =>
      (super.noSuchMethod(
            Invocation.getter(#topRatedController),
            returnValue: _FakeScrollController_1(
              this,
              Invocation.getter(#topRatedController),
            ),
          )
          as _i3.ScrollController);

  @override
  _i4.GetAiringTodayTv get getAiringTodayTv =>
      (super.noSuchMethod(
            Invocation.getter(#getAiringTodayTv),
            returnValue: _FakeGetAiringTodayTv_2(
              this,
              Invocation.getter(#getAiringTodayTv),
            ),
          )
          as _i4.GetAiringTodayTv);

  @override
  _i5.GetOnTheAirTv get getOnTheAirTv =>
      (super.noSuchMethod(
            Invocation.getter(#getOnTheAirTv),
            returnValue: _FakeGetOnTheAirTv_3(
              this,
              Invocation.getter(#getOnTheAirTv),
            ),
          )
          as _i5.GetOnTheAirTv);

  @override
  _i6.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_4(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i6.GetPopularTv);

  @override
  _i7.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_5(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i7.GetTopRatedTv);

  @override
  List<_i10.TvSeries> get airingTodayTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#airingTodayTvSeries),
            returnValue: <_i10.TvSeries>[],
          )
          as List<_i10.TvSeries>);

  @override
  List<_i10.TvSeries> get onTheAirTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#onTheAirTvSeries),
            returnValue: <_i10.TvSeries>[],
          )
          as List<_i10.TvSeries>);

  @override
  List<_i10.TvSeries> get popularTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#popularTvSeries),
            returnValue: <_i10.TvSeries>[],
          )
          as List<_i10.TvSeries>);

  @override
  List<_i10.TvSeries> get topRatedTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#topRatedTvSeries),
            returnValue: <_i10.TvSeries>[],
          )
          as List<_i10.TvSeries>);

  @override
  _i11.RequestState get airingTodayState =>
      (super.noSuchMethod(
            Invocation.getter(#airingTodayState),
            returnValue: _i11.RequestState.Empty,
          )
          as _i11.RequestState);

  @override
  _i11.RequestState get onTheAirState =>
      (super.noSuchMethod(
            Invocation.getter(#onTheAirState),
            returnValue: _i11.RequestState.Empty,
          )
          as _i11.RequestState);

  @override
  _i11.RequestState get popularTvState =>
      (super.noSuchMethod(
            Invocation.getter(#popularTvState),
            returnValue: _i11.RequestState.Empty,
          )
          as _i11.RequestState);

  @override
  _i11.RequestState get topRatedTvState =>
      (super.noSuchMethod(
            Invocation.getter(#topRatedTvState),
            returnValue: _i11.RequestState.Empty,
          )
          as _i11.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  int get airingTodayPage =>
      (super.noSuchMethod(Invocation.getter(#airingTodayPage), returnValue: 0)
          as int);

  @override
  bool get hasMoreAiringToday =>
      (super.noSuchMethod(
            Invocation.getter(#hasMoreAiringToday),
            returnValue: false,
          )
          as bool);

  @override
  bool get isFetching =>
      (super.noSuchMethod(Invocation.getter(#isFetching), returnValue: false)
          as bool);

  @override
  set refreshC(_i2.RefreshController? _refreshC) => super.noSuchMethod(
    Invocation.setter(#refreshC, _refreshC),
    returnValueForMissingStub: null,
  );

  @override
  set airingTodayTvSeries(List<_i10.TvSeries>? value) => super.noSuchMethod(
    Invocation.setter(#airingTodayTvSeries, value),
    returnValueForMissingStub: null,
  );

  @override
  set airingTodayPage(int? value) => super.noSuchMethod(
    Invocation.setter(#airingTodayPage, value),
    returnValueForMissingStub: null,
  );

  @override
  set hasMoreAiringToday(bool? value) => super.noSuchMethod(
    Invocation.setter(#hasMoreAiringToday, value),
    returnValueForMissingStub: null,
  );

  @override
  set isFetching(bool? value) => super.noSuchMethod(
    Invocation.setter(#isFetching, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void init() => super.noSuchMethod(
    Invocation.method(#init, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> loadTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#loadTvSeries, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loadMoreTvAiringToday() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreTvAiringToday, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loadMoreTvOnTheAir() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreTvOnTheAir, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loadMoreTvPopular() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreTvPopular, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loadMoreTvTopRated() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreTvTopRated, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> onRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#onRefresh, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> fetchTvSeriesAiringToday() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesAiringToday, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> fetchTvSeriesOnTheAir() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesOnTheAir, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> fetchTvSeriesPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesPopularTv, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> fetchTvSeriesTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesTopRatedTv, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSearchNotifier extends _i1.Mock implements _i15.TvSearchNotifier {
  MockTvSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SearchTvSeries get searchTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#searchTvSeries),
            returnValue: _FakeSearchTvSeries_6(
              this,
              Invocation.getter(#searchTvSeries),
            ),
          )
          as _i8.SearchTvSeries);

  @override
  _i11.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i11.RequestState.Empty,
          )
          as _i11.RequestState);

  @override
  List<_i10.TvSeries> get searchResult =>
      (super.noSuchMethod(
            Invocation.getter(#searchResult),
            returnValue: <_i10.TvSeries>[],
          )
          as List<_i10.TvSeries>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i13.Future<void> fetchTvSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSearch, [query]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
