// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/tv_series/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i14;

import 'package:bloc/bloc.dart' as _i15;
import 'package:ditonton_clean_architecture/common/state_enum.dart' as _i9;
import 'package:ditonton_clean_architecture/domain/entities/tv/tv_detail.dart'
    as _i13;
import 'package:ditonton_clean_architecture/domain/entities/tv/tv_series.dart'
    as _i10;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_tv_detail.dart'
    as _i2;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_tv_recommendations.dart'
    as _i3;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_watchlist_status_tv.dart'
    as _i4;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/remove_watchlist_tv.dart'
    as _i6;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/save_watchlist_tv.dart'
    as _i5;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_detail/tv_detail_bloc.dart'
    as _i7;
import 'package:ditonton_clean_architecture/presentation/provider/tv_series/tv_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvDetail_0 extends _i1.SmartFake implements _i2.GetTvDetail {
  _FakeGetTvDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTvRecommendations {
  _FakeGetTvRecommendations_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatusTv_2 extends _i1.SmartFake
    implements _i4.GetWatchListStatusTv {
  _FakeGetWatchListStatusTv_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTv_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistTv {
  _FakeSaveWatchlistTv_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTv_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistTv {
  _FakeRemoveWatchlistTv_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvDetailState_5 extends _i1.SmartFake implements _i7.TvDetailState {
  _FakeTvDetailState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailNotifier extends _i1.Mock implements _i8.TvDetailNotifier {
  MockTvDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvDetail get getTvDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTvDetail),
            returnValue: _FakeGetTvDetail_0(
              this,
              Invocation.getter(#getTvDetail),
            ),
          )
          as _i2.GetTvDetail);

  @override
  _i3.GetTvRecommendations get getTvRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTvRecommendations),
            returnValue: _FakeGetTvRecommendations_1(
              this,
              Invocation.getter(#getTvRecommendations),
            ),
          )
          as _i3.GetTvRecommendations);

  @override
  _i4.GetWatchListStatusTv get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatusTv_2(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i4.GetWatchListStatusTv);

  @override
  _i5.SaveWatchlistTv get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlistTv_3(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i5.SaveWatchlistTv);

  @override
  _i6.RemoveWatchlistTv get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlistTv_4(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i6.RemoveWatchlistTv);

  @override
  _i9.RequestState get tvState =>
      (super.noSuchMethod(
            Invocation.getter(#tvState),
            returnValue: _i9.RequestState.Empty,
          )
          as _i9.RequestState);

  @override
  List<_i10.TvSeries> get tvRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#tvRecommendations),
            returnValue: <_i10.TvSeries>[],
          )
          as List<_i10.TvSeries>);

  @override
  _i9.RequestState get recommendationState =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationState),
            returnValue: _i9.RequestState.Empty,
          )
          as _i9.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#isAddedToWatchlist),
            returnValue: false,
          )
          as bool);

  @override
  String get watchlistMessage =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistMessage),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#watchlistMessage),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> fetchTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvDetail, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addWatchlist(_i13.TvDetail? tvDetail) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlist, [tvDetail]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> removeFromWatchlist(_i13.TvDetail? tvDetail) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [tvDetail]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailBloc extends _i1.Mock implements _i7.TvDetailBloc {
  MockTvDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvDetail get getTvDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTvDetail),
            returnValue: _FakeGetTvDetail_0(
              this,
              Invocation.getter(#getTvDetail),
            ),
          )
          as _i2.GetTvDetail);

  @override
  _i3.GetTvRecommendations get getTvRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTvRecommendations),
            returnValue: _FakeGetTvRecommendations_1(
              this,
              Invocation.getter(#getTvRecommendations),
            ),
          )
          as _i3.GetTvRecommendations);

  @override
  _i4.GetWatchListStatusTv get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatusTv_2(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i4.GetWatchListStatusTv);

  @override
  _i5.SaveWatchlistTv get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlistTv_3(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i5.SaveWatchlistTv);

  @override
  _i6.RemoveWatchlistTv get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlistTv_4(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i6.RemoveWatchlistTv);

  @override
  _i7.TvDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvDetailState_5(this, Invocation.getter(#state)),
          )
          as _i7.TvDetailState);

  @override
  _i12.Stream<_i7.TvDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i7.TvDetailState>.empty(),
          )
          as _i12.Stream<_i7.TvDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.TvDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.TvDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.TvDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.TvDetailEvent>(
    _i15.EventHandler<E, _i7.TvDetailState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i7.TvDetailEvent, _i7.TvDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void onChange(_i15.Change<_i7.TvDetailState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
