// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/tv_series/tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:bloc/bloc.dart' as _i11;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_airing_today_tv.dart'
    as _i2;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_on_the_air_tv.dart'
    as _i4;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_popular_tv.dart'
    as _i6;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_top_rated_tv.dart'
    as _i8;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_list/airing_today/airing_today_tv_bloc.dart'
    as _i3;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_list/on_the_air/on_the_air_tv_bloc.dart'
    as _i5;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_list/popular/popular_tv_bloc.dart'
    as _i7;
import 'package:ditonton_clean_architecture/presentation/bloc/tv/tv_list/top_rated/top_rated_tv_bloc.dart'
    as _i9;
import 'package:flutter/src/widgets/navigator.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAiringTodayTv_0 extends _i1.SmartFake
    implements _i2.GetAiringTodayTv {
  _FakeGetAiringTodayTv_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiringTodayTvState_1 extends _i1.SmartFake
    implements _i3.AiringTodayTvState {
  _FakeAiringTodayTvState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTv_2 extends _i1.SmartFake implements _i4.GetOnTheAirTv {
  _FakeGetOnTheAirTv_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnTheAirTvState_3 extends _i1.SmartFake
    implements _i5.OnTheAirTvState {
  _FakeOnTheAirTvState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTv_4 extends _i1.SmartFake implements _i6.GetPopularTv {
  _FakeGetPopularTv_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTvState_5 extends _i1.SmartFake
    implements _i7.PopularTvState {
  _FakePopularTvState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTv_6 extends _i1.SmartFake implements _i8.GetTopRatedTv {
  _FakeGetTopRatedTv_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTvState_7 extends _i1.SmartFake
    implements _i9.TopRatedTvState {
  _FakeTopRatedTvState_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiringTodayTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiringTodayTvBloc extends _i1.Mock implements _i3.AiringTodayTvBloc {
  MockAiringTodayTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAiringTodayTv get getAiringTodayTv =>
      (super.noSuchMethod(
            Invocation.getter(#getAiringTodayTv),
            returnValue: _FakeGetAiringTodayTv_0(
              this,
              Invocation.getter(#getAiringTodayTv),
            ),
          )
          as _i2.GetAiringTodayTv);

  @override
  _i3.AiringTodayTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAiringTodayTvState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AiringTodayTvState);

  @override
  _i10.Stream<_i3.AiringTodayTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i3.AiringTodayTvState>.empty(),
          )
          as _i10.Stream<_i3.AiringTodayTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.AiringTodayTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.AiringTodayTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AiringTodayTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.AiringTodayTvEvent>(
    _i11.EventHandler<E, _i3.AiringTodayTvState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i3.AiringTodayTvEvent, _i3.AiringTodayTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onChange(_i11.Change<_i3.AiringTodayTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnTheAirTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvBloc extends _i1.Mock implements _i5.OnTheAirTvBloc {
  MockOnTheAirTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetOnTheAirTv get getOnTheAirTv =>
      (super.noSuchMethod(
            Invocation.getter(#getOnTheAirTv),
            returnValue: _FakeGetOnTheAirTv_2(
              this,
              Invocation.getter(#getOnTheAirTv),
            ),
          )
          as _i4.GetOnTheAirTv);

  @override
  _i5.OnTheAirTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOnTheAirTvState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.OnTheAirTvState);

  @override
  _i10.Stream<_i5.OnTheAirTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i5.OnTheAirTvState>.empty(),
          )
          as _i10.Stream<_i5.OnTheAirTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i5.OnTheAirTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.OnTheAirTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.OnTheAirTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.OnTheAirTvEvent>(
    _i11.EventHandler<E, _i5.OnTheAirTvState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i5.OnTheAirTvEvent, _i5.OnTheAirTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onChange(_i11.Change<_i5.OnTheAirTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvBloc extends _i1.Mock implements _i7.PopularTvBloc {
  MockPopularTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_4(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i6.GetPopularTv);

  @override
  _i7.PopularTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularTvState_5(this, Invocation.getter(#state)),
          )
          as _i7.PopularTvState);

  @override
  _i10.Stream<_i7.PopularTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i7.PopularTvState>.empty(),
          )
          as _i10.Stream<_i7.PopularTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.PopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.PopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.PopularTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.PopularTvEvent>(
    _i11.EventHandler<E, _i7.PopularTvState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i7.PopularTvEvent, _i7.PopularTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onChange(_i11.Change<_i7.PopularTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvBloc extends _i1.Mock implements _i9.TopRatedTvBloc {
  MockTopRatedTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_6(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i8.GetTopRatedTv);

  @override
  _i9.TopRatedTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedTvState_7(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i9.TopRatedTvState);

  @override
  _i10.Stream<_i9.TopRatedTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i9.TopRatedTvState>.empty(),
          )
          as _i10.Stream<_i9.TopRatedTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i9.TopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.TopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i9.TopRatedTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.TopRatedTvEvent>(
    _i11.EventHandler<E, _i9.TopRatedTvState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i9.TopRatedTvEvent, _i9.TopRatedTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onChange(_i11.Change<_i9.TopRatedTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i12.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i12.Route<dynamic>? route, _i12.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i12.Route<dynamic>? newRoute,
    _i12.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i12.Route<dynamic>? topRoute,
    _i12.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
