// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/tv_series/watchlist_tv_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:ditonton_clean_architecture/common/state_enum.dart' as _i7;
import 'package:ditonton_clean_architecture/domain/entities/tv/tv_series.dart'
    as _i6;
import 'package:ditonton_clean_architecture/domain/usecases/tv_series/get_watchlist_tv.dart'
    as _i2;
import 'package:ditonton_clean_architecture/presentation/provider/tv_series/watchlist_tv_notifier.dart'
    as _i5;
import 'package:flutter/foundation.dart' as _i4;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetWatchlistTv_0 extends _i1.SmartFake
    implements _i2.GetWatchlistTv {
  _FakeGetWatchlistTv_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteSettings_1 extends _i1.SmartFake implements _i3.RouteSettings {
  _FakeRouteSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueListenable_2<T1> extends _i1.SmartFake
    implements _i4.ValueListenable<T1> {
  _FakeValueListenable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTickerFuture_3 extends _i1.SmartFake implements _i3.TickerFuture {
  _FakeTickerFuture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WatchlistTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvNotifier extends _i1.Mock
    implements _i5.WatchlistTvNotifier {
  @override
  _i2.GetWatchlistTv get getWatchlistTv =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistTv),
            returnValue: _FakeGetWatchlistTv_0(
              this,
              Invocation.getter(#getWatchlistTv),
            ),
            returnValueForMissingStub: _FakeGetWatchlistTv_0(
              this,
              Invocation.getter(#getWatchlistTv),
            ),
          )
          as _i2.GetWatchlistTv);

  @override
  List<_i6.TvSeries> get watchlistTv =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistTv),
            returnValue: <_i6.TvSeries>[],
            returnValueForMissingStub: <_i6.TvSeries>[],
          )
          as List<_i6.TvSeries>);

  @override
  _i7.RequestState get watchlistState =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistState),
            returnValue: _i7.RequestState.Empty,
            returnValueForMissingStub: _i7.RequestState.Empty,
          )
          as _i7.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Future<void> fetchWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchlistTv, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i3.NavigatorObserver {
  @override
  void didPush(_i3.Route<dynamic>? route, _i3.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPush, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(_i3.Route<dynamic>? route, _i3.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i3.Route<dynamic>? route,
    _i3.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i3.Route<dynamic>? newRoute,
    _i3.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i3.Route<dynamic>? topRoute,
    _i3.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i3.Route<dynamic>? route,
    _i3.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Route].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoute<T> extends _i1.Mock implements _i3.Route<T> {
  @override
  bool get requestFocus =>
      (super.noSuchMethod(
            Invocation.getter(#requestFocus),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.RouteSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeRouteSettings_1(
              this,
              Invocation.getter(#settings),
            ),
            returnValueForMissingStub: _FakeRouteSettings_1(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i3.RouteSettings);

  @override
  _i4.ValueListenable<String?> get restorationScopeId =>
      (super.noSuchMethod(
            Invocation.getter(#restorationScopeId),
            returnValue: _FakeValueListenable_2<String?>(
              this,
              Invocation.getter(#restorationScopeId),
            ),
            returnValueForMissingStub: _FakeValueListenable_2<String?>(
              this,
              Invocation.getter(#restorationScopeId),
            ),
          )
          as _i4.ValueListenable<String?>);

  @override
  List<_i3.OverlayEntry> get overlayEntries =>
      (super.noSuchMethod(
            Invocation.getter(#overlayEntries),
            returnValue: <_i3.OverlayEntry>[],
            returnValueForMissingStub: <_i3.OverlayEntry>[],
          )
          as List<_i3.OverlayEntry>);

  @override
  _i3.RoutePopDisposition get popDisposition =>
      (super.noSuchMethod(
            Invocation.getter(#popDisposition),
            returnValue: _i3.RoutePopDisposition.pop,
            returnValueForMissingStub: _i3.RoutePopDisposition.pop,
          )
          as _i3.RoutePopDisposition);

  @override
  bool get willHandlePopInternally =>
      (super.noSuchMethod(
            Invocation.getter(#willHandlePopInternally),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Future<T?> get popped =>
      (super.noSuchMethod(
            Invocation.getter(#popped),
            returnValue: _i9.Future<T?>.value(),
            returnValueForMissingStub: _i9.Future<T?>.value(),
          )
          as _i9.Future<T?>);

  @override
  bool get isCurrent =>
      (super.noSuchMethod(
            Invocation.getter(#isCurrent),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isFirst =>
      (super.noSuchMethod(
            Invocation.getter(#isFirst),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasActiveRouteBelow =>
      (super.noSuchMethod(
            Invocation.getter(#hasActiveRouteBelow),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isActive =>
      (super.noSuchMethod(
            Invocation.getter(#isActive),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void install() => super.noSuchMethod(
    Invocation.method(#install, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.TickerFuture didPush() =>
      (super.noSuchMethod(
            Invocation.method(#didPush, []),
            returnValue: _FakeTickerFuture_3(
              this,
              Invocation.method(#didPush, []),
            ),
            returnValueForMissingStub: _FakeTickerFuture_3(
              this,
              Invocation.method(#didPush, []),
            ),
          )
          as _i3.TickerFuture);

  @override
  void didAdd() => super.noSuchMethod(
    Invocation.method(#didAdd, []),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace(_i3.Route<dynamic>? oldRoute) => super.noSuchMethod(
    Invocation.method(#didReplace, [oldRoute]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i3.RoutePopDisposition> willPop() =>
      (super.noSuchMethod(
            Invocation.method(#willPop, []),
            returnValue: _i9.Future<_i3.RoutePopDisposition>.value(
              _i3.RoutePopDisposition.pop,
            ),
            returnValueForMissingStub:
                _i9.Future<_i3.RoutePopDisposition>.value(
                  _i3.RoutePopDisposition.pop,
                ),
          )
          as _i9.Future<_i3.RoutePopDisposition>);

  @override
  void onPopInvoked(bool? didPop) => super.noSuchMethod(
    Invocation.method(#onPopInvoked, [didPop]),
    returnValueForMissingStub: null,
  );

  @override
  void onPopInvokedWithResult(bool? didPop, T? result) => super.noSuchMethod(
    Invocation.method(#onPopInvokedWithResult, [didPop, result]),
    returnValueForMissingStub: null,
  );

  @override
  bool didPop(T? result) =>
      (super.noSuchMethod(
            Invocation.method(#didPop, [result]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void didComplete(T? result) => super.noSuchMethod(
    Invocation.method(#didComplete, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void didPopNext(_i3.Route<dynamic>? nextRoute) => super.noSuchMethod(
    Invocation.method(#didPopNext, [nextRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeNext(_i3.Route<dynamic>? nextRoute) => super.noSuchMethod(
    Invocation.method(#didChangeNext, [nextRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePrevious(_i3.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didChangePrevious, [previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void changedInternalState() => super.noSuchMethod(
    Invocation.method(#changedInternalState, []),
    returnValueForMissingStub: null,
  );

  @override
  void changedExternalState() => super.noSuchMethod(
    Invocation.method(#changedExternalState, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
