// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/presentation/pages/up_coming_movies_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i11;

import 'package:bloc/bloc.dart' as _i12;
import 'package:ditonton_clean_architecture/common/state_enum.dart' as _i7;
import 'package:ditonton_clean_architecture/domain/entities/movies/movie.dart'
    as _i8;
import 'package:ditonton_clean_architecture/domain/usecases/movies/get_up_coming_movies.dart'
    as _i2;
import 'package:ditonton_clean_architecture/presentation/bloc/movies/see_more_upcoming/see_more_upcoming_movie_bloc.dart'
    as _i5;
import 'package:ditonton_clean_architecture/presentation/provider/movies/up_coming_movies_notifier.dart'
    as _i6;
import 'package:flutter/cupertino.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:pull_to_refresh/pull_to_refresh.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetUpComingMovies_0 extends _i1.SmartFake
    implements _i2.GetUpComingMovies {
  _FakeGetUpComingMovies_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshController_1 extends _i1.SmartFake
    implements _i3.RefreshController {
  _FakeRefreshController_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScrollController_2 extends _i1.SmartFake
    implements _i4.ScrollController {
  _FakeScrollController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeeMoreUpcomingMovieState_3 extends _i1.SmartFake
    implements _i5.SeeMoreUpcomingMovieState {
  _FakeSeeMoreUpcomingMovieState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UpComingMoviesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpComingMoviesNotifier extends _i1.Mock
    implements _i6.UpComingMoviesNotifier {
  MockUpComingMoviesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetUpComingMovies get getUpComingMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getUpComingMovies),
            returnValue: _FakeGetUpComingMovies_0(
              this,
              Invocation.getter(#getUpComingMovies),
            ),
          )
          as _i2.GetUpComingMovies);

  @override
  _i3.RefreshController get refreshC =>
      (super.noSuchMethod(
            Invocation.getter(#refreshC),
            returnValue: _FakeRefreshController_1(
              this,
              Invocation.getter(#refreshC),
            ),
          )
          as _i3.RefreshController);

  @override
  _i4.ScrollController get scrollController =>
      (super.noSuchMethod(
            Invocation.getter(#scrollController),
            returnValue: _FakeScrollController_2(
              this,
              Invocation.getter(#scrollController),
            ),
          )
          as _i4.ScrollController);

  @override
  _i7.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i7.RequestState.Empty,
          )
          as _i7.RequestState);

  @override
  List<_i8.Movie> get movies =>
      (super.noSuchMethod(
            Invocation.getter(#movies),
            returnValue: <_i8.Movie>[],
          )
          as List<_i8.Movie>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get isFetching =>
      (super.noSuchMethod(Invocation.getter(#isFetching), returnValue: false)
          as bool);

  @override
  set refreshC(_i3.RefreshController? _refreshC) => super.noSuchMethod(
    Invocation.setter(#refreshC, _refreshC),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> loadMoreMovieUpComing() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreMovieUpComing, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadMovies() =>
      (super.noSuchMethod(
            Invocation.method(#loadMovies, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> onRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#onRefresh, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> fetchUpComingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUpComingMovies, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SeeMoreUpcomingMovieBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeeMoreUpcomingMovieBloc extends _i1.Mock
    implements _i5.SeeMoreUpcomingMovieBloc {
  MockSeeMoreUpcomingMovieBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetUpComingMovies get getUpComingMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getUpComingMovies),
            returnValue: _FakeGetUpComingMovies_0(
              this,
              Invocation.getter(#getUpComingMovies),
            ),
          )
          as _i2.GetUpComingMovies);

  @override
  _i5.SeeMoreUpcomingMovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSeeMoreUpcomingMovieState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.SeeMoreUpcomingMovieState);

  @override
  _i10.Stream<_i5.SeeMoreUpcomingMovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i5.SeeMoreUpcomingMovieState>.empty(),
          )
          as _i10.Stream<_i5.SeeMoreUpcomingMovieState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i4.ScrollController? controller, _i11.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i5.SeeMoreUpcomingMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.SeeMoreUpcomingMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.SeeMoreUpcomingMovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.SeeMoreUpcomingMovieEvent>(
    _i12.EventHandler<E, _i5.SeeMoreUpcomingMovieState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<
      _i5.SeeMoreUpcomingMovieEvent,
      _i5.SeeMoreUpcomingMovieState
    >?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onChange(_i12.Change<_i5.SeeMoreUpcomingMovieState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
