// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_clean_architecture/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i26;
import 'dart:typed_data' as _i27;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton_clean_architecture/common/failure.dart' as _i8;
import 'package:ditonton_clean_architecture/common/network_info.dart' as _i19;
import 'package:ditonton_clean_architecture/data/datasources/db/database_helper.dart'
    as _i16;
import 'package:ditonton_clean_architecture/data/datasources/movies/movie_local_data_source.dart'
    as _i13;
import 'package:ditonton_clean_architecture/data/datasources/movies/movie_remote_data_source.dart'
    as _i11;
import 'package:ditonton_clean_architecture/data/datasources/tv_series/tv_series_local_data_source.dart'
    as _i25;
import 'package:ditonton_clean_architecture/data/datasources/tv_series/tv_series_remote_data_source.dart'
    as _i23;
import 'package:ditonton_clean_architecture/data/models/movies/movie_detail_model.dart'
    as _i3;
import 'package:ditonton_clean_architecture/data/models/movies/movie_model.dart'
    as _i12;
import 'package:ditonton_clean_architecture/data/models/movies/movie_table.dart'
    as _i14;
import 'package:ditonton_clean_architecture/data/models/tv_series/tv_detail_model.dart'
    as _i4;
import 'package:ditonton_clean_architecture/data/models/tv_series/tv_model.dart'
    as _i24;
import 'package:ditonton_clean_architecture/data/models/tv_series/tv_series_table.dart'
    as _i18;
import 'package:ditonton_clean_architecture/domain/entities/movies/movie.dart'
    as _i9;
import 'package:ditonton_clean_architecture/domain/entities/movies/movie_detail.dart'
    as _i10;
import 'package:ditonton_clean_architecture/domain/entities/tv/tv_detail.dart'
    as _i22;
import 'package:ditonton_clean_architecture/domain/entities/tv/tv_series.dart'
    as _i21;
import 'package:ditonton_clean_architecture/domain/repositories/movie_repository.dart'
    as _i6;
import 'package:ditonton_clean_architecture/domain/repositories/tv_series_repository.dart'
    as _i20;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:sqflite/sqflite.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvDetailResponse_2 extends _i1.SmartFake
    implements _i4.TvDetailResponse {
  _FakeTvDetailResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i6.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getNowPlayingMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getPopularMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getTopRatedMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getUpComingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getUpComingMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getUpComingMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetail>>.value(
                  _FakeEither_0<_i8.Failure, _i10.MovieDetail>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetail>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getMovieRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getMovieRecommendations, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#searchMovies, [query]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveWatchlist(
    _i10.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [movie]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeWatchlist(
    _i10.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#getWatchlistMovies, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i11.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i12.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i7.Future<List<_i12.MovieModel>>.value(
              <_i12.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<List<_i12.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i7.Future<List<_i12.MovieModel>>.value(
              <_i12.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<List<_i12.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i7.Future<List<_i12.MovieModel>>.value(
              <_i12.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<List<_i12.MovieModel>> getUpComingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getUpComingMovies, []),
            returnValue: _i7.Future<List<_i12.MovieModel>>.value(
              <_i12.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i7.Future<_i3.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_1(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.MovieDetailResponse>);

  @override
  _i7.Future<List<_i12.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i7.Future<List<_i12.MovieModel>>.value(
              <_i12.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<List<_i12.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i7.Future<List<_i12.MovieModel>>.value(
              <_i12.MovieModel>[],
            ),
          )
          as _i7.Future<List<_i12.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i13.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> cacheNowPlayingMovies(List<_i14.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheNowPlayingMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cachePopularMovies(List<_i14.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cachePopularMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheTopRatedMovies(List<_i14.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTopRatedMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheUpComingMovies(List<_i14.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUpComingMovies, [movies]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i14.MovieTable>> getCachedNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedNowPlayingMovies, []),
            returnValue: _i7.Future<List<_i14.MovieTable>>.value(
              <_i14.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i14.MovieTable>>);

  @override
  _i7.Future<List<_i14.MovieTable>> getCachedPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPopularMovies, []),
            returnValue: _i7.Future<List<_i14.MovieTable>>.value(
              <_i14.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i14.MovieTable>>);

  @override
  _i7.Future<List<_i14.MovieTable>> getCachedTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTopRatedMovies, []),
            returnValue: _i7.Future<List<_i14.MovieTable>>.value(
              <_i14.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i14.MovieTable>>);

  @override
  _i7.Future<List<_i14.MovieTable>> getCachedUpComingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUpComingMovies, []),
            returnValue: _i7.Future<List<_i14.MovieTable>>.value(
              <_i14.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i14.MovieTable>>);

  @override
  _i7.Future<String> insertWatchlist(_i14.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i7.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> removeWatchlist(_i14.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i7.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i14.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i7.Future<_i14.MovieTable?>.value(),
          )
          as _i7.Future<_i14.MovieTable?>);

  @override
  _i7.Future<List<_i14.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i7.Future<List<_i14.MovieTable>>.value(
              <_i14.MovieTable>[],
            ),
          )
          as _i7.Future<List<_i14.MovieTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i16.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i17.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i17.Database?>.value(),
          )
          as _i7.Future<_i17.Database?>);

  @override
  _i7.Future<void> insertCacheTransaction(
    List<_i14.MovieTable>? movies,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransaction, [movies, category]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheMovies, [category]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> insertWatchlist(_i14.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlist(_i14.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> insertCacheTransactionTvSeries(
    List<_i18.TvSeriesTable>? tvSeries,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransactionTvSeries, [
              tvSeries,
              category,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheTvSeries(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheTvSeries, [category]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> clearCacheTvSeries(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCacheTvSeries, [category]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> insertWatchlistTv(_i18.TvSeriesTable? tvTable) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistTv, [tvTable]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlistTv(_i18.TvSeriesTable? tvTable) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistTv, [tvTable]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i19.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i20.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>> getAiringToday() =>
      (super.noSuchMethod(
            Invocation.method(#getAiringToday, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i21.TvSeries>>(
                    this,
                    Invocation.method(#getAiringToday, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>> getOnTheAir() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAir, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i21.TvSeries>>(
                    this,
                    Invocation.method(#getOnTheAir, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i22.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, _i22.TvDetail>>.value(
                  _FakeEither_0<_i8.Failure, _i22.TvDetail>(
                    this,
                    Invocation.method(#getTvDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, _i22.TvDetail>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>> getTvRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i21.TvSeries>>(
                    this,
                    Invocation.method(#getTvRecommendations, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i21.TvSeries>>(
                    this,
                    Invocation.method(#searchTvSeries, [query]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveWatchlist(
    _i22.TvDetail? tv,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tv]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tv]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeWatchlist(
    _i22.TvDetail? tv,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tv]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>> getWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTv, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i21.TvSeries>>(
                    this,
                    Invocation.method(#getWatchlistTv, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i21.TvSeries>>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i23.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i24.TvModel>> getAiringToday() =>
      (super.noSuchMethod(
            Invocation.method(#getAiringToday, []),
            returnValue: _i7.Future<List<_i24.TvModel>>.value(<_i24.TvModel>[]),
          )
          as _i7.Future<List<_i24.TvModel>>);

  @override
  _i7.Future<List<_i24.TvModel>> getOnTheAir() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAir, []),
            returnValue: _i7.Future<List<_i24.TvModel>>.value(<_i24.TvModel>[]),
          )
          as _i7.Future<List<_i24.TvModel>>);

  @override
  _i7.Future<_i4.TvDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue: _i7.Future<_i4.TvDetailResponse>.value(
              _FakeTvDetailResponse_2(
                this,
                Invocation.method(#getTvDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.TvDetailResponse>);

  @override
  _i7.Future<List<_i24.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue: _i7.Future<List<_i24.TvModel>>.value(<_i24.TvModel>[]),
          )
          as _i7.Future<List<_i24.TvModel>>);

  @override
  _i7.Future<List<_i24.TvModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i7.Future<List<_i24.TvModel>>.value(<_i24.TvModel>[]),
          )
          as _i7.Future<List<_i24.TvModel>>);
}

/// A class which mocks [TvSeriesLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDatasource extends _i1.Mock
    implements _i25.TvSeriesLocalDatasource {
  MockTvSeriesLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> cacheAiringTodayTvSeries(List<_i18.TvSeriesTable>? tv) =>
      (super.noSuchMethod(
            Invocation.method(#cacheAiringTodayTvSeries, [tv]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheOnTheAirTvSeries(List<_i18.TvSeriesTable>? tv) =>
      (super.noSuchMethod(
            Invocation.method(#cacheOnTheAirTvSeries, [tv]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i18.TvSeriesTable>> getCachedAiringTodayTv() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAiringTodayTv, []),
            returnValue: _i7.Future<List<_i18.TvSeriesTable>>.value(
              <_i18.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i18.TvSeriesTable>>);

  @override
  _i7.Future<List<_i18.TvSeriesTable>> getCachedOnTheAirTv() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOnTheAirTv, []),
            returnValue: _i7.Future<List<_i18.TvSeriesTable>>.value(
              <_i18.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i18.TvSeriesTable>>);

  @override
  _i7.Future<String> insertWatchlist(_i18.TvSeriesTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tv]),
            returnValue: _i7.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tv]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> removeWatchlist(_i18.TvSeriesTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i7.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tv]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i18.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i7.Future<_i18.TvSeriesTable?>.value(),
          )
          as _i7.Future<_i18.TvSeriesTable?>);

  @override
  _i7.Future<List<_i18.TvSeriesTable>> getWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTv, []),
            returnValue: _i7.Future<List<_i18.TvSeriesTable>>.value(
              <_i18.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i18.TvSeriesTable>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i26.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i26.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i26.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i26.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i7.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i27.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i7.Future<_i27.Uint8List>.value(_i27.Uint8List(0)),
          )
          as _i7.Future<_i27.Uint8List>);

  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i7.Future<_i5.StreamedResponse>.value(
              _FakeStreamedResponse_4(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
