// Mocks generated by Mockito 5.4.6 from annotations
// in tv_series/test/helpers/test_helper_tv.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i13;
import 'dart:typed_data' as _i14;
import 'dart:ui' as _i11;

import 'package:bloc/bloc.dart' as _i12;
import 'package:core/module/core.dart' as _i6;
import 'package:dartz/dartz.dart' as _i4;
import 'package:flutter/material.dart' as _i10;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:movies/module/movies.dart' as _i8;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i2;
import 'package:tv_series/module/tv_series.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvDetailResponse {
  _FakeTvDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailTable_2 extends _i1.SmartFake
    implements _i3.TvSeriesDetailTable {
  _FakeTvSeriesDetailTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesRepository_4 extends _i1.SmartFake
    implements _i3.TvSeriesRepository {
  _FakeTvSeriesRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTv_5 extends _i1.SmartFake implements _i3.GetOnTheAirTv {
  _FakeGetOnTheAirTv_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeeMoreOnTheAirTvState_6 extends _i1.SmartFake
    implements _i3.SeeMoreOnTheAirTvState {
  _FakeSeeMoreOnTheAirTvState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTv_7 extends _i1.SmartFake implements _i3.GetPopularTv {
  _FakeGetPopularTv_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeeMorePopularTvState_8 extends _i1.SmartFake
    implements _i3.SeeMorePopularTvState {
  _FakeSeeMorePopularTvState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchTvSeries_9 extends _i1.SmartFake
    implements _i3.SearchTvSeries {
  _FakeSearchTvSeries_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSearchState_10 extends _i1.SmartFake implements _i3.TvSearchState {
  _FakeTvSearchState_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTv_11 extends _i1.SmartFake implements _i3.GetTopRatedTv {
  _FakeGetTopRatedTv_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeeMoreTopRatedTvState_12 extends _i1.SmartFake
    implements _i3.SeeMoreTopRatedTvState {
  _FakeSeeMoreTopRatedTvState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvDetail_13 extends _i1.SmartFake implements _i3.GetTvDetail {
  _FakeGetTvDetail_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvRecommendations_14 extends _i1.SmartFake
    implements _i3.GetTvRecommendations {
  _FakeGetTvRecommendations_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatusTv_15 extends _i1.SmartFake
    implements _i3.GetWatchListStatusTv {
  _FakeGetWatchListStatusTv_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTv_16 extends _i1.SmartFake
    implements _i3.SaveWatchlistTv {
  _FakeSaveWatchlistTv_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTv_17 extends _i1.SmartFake
    implements _i3.RemoveWatchlistTv {
  _FakeRemoveWatchlistTv_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvDetailState_18 extends _i1.SmartFake implements _i3.TvDetailState {
  _FakeTvDetailState_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAiringTodayTv_19 extends _i1.SmartFake
    implements _i3.GetAiringTodayTv {
  _FakeGetAiringTodayTv_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiringTodayTvState_20 extends _i1.SmartFake
    implements _i3.AiringTodayTvState {
  _FakeAiringTodayTvState_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnTheAirTvState_21 extends _i1.SmartFake
    implements _i3.OnTheAirTvState {
  _FakeOnTheAirTvState_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTvState_22 extends _i1.SmartFake
    implements _i3.PopularTvState {
  _FakePopularTvState_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTvState_23 extends _i1.SmartFake
    implements _i3.TopRatedTvState {
  _FakeTopRatedTvState_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTv_24 extends _i1.SmartFake
    implements _i3.GetWatchlistTv {
  _FakeGetWatchlistTv_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistTvState_25 extends _i1.SmartFake
    implements _i3.WatchlistTvState {
  _FakeWatchlistTvState_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_26 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_27 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i6.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i7.Future<_i2.Database>);

  @override
  _i7.Future<void> insertCacheTransaction(
    List<_i8.MovieTable>? movies,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransaction, [movies, category]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> insertCacheMovieDetail(_i8.MovieDetailTable? movieDetail) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheMovieDetail, [movieDetail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> getCachedMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMovieDetail, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> insertCacheTvDetail(_i3.TvSeriesDetailTable? tvDetail) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTvDetail, [tvDetail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> getCachedTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTvDetail, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheMovies, [category]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> insertWatchlistMovie(_i8.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistMovie, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlistMovie(_i8.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistMovie, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> insertCacheTransactionTvSeries(
    List<_i3.TvSeriesTable>? tvSeries,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransactionTvSeries, [
              tvSeries,
              category,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheTvSeries(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheTvSeries, [category]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> clearCacheTvSeries(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCacheTvSeries, [category]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> insertWatchlistTv(_i3.TvSeriesTable? tvTable) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistTv, [tvTable]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlistTv(_i3.TvSeriesTable? tvTable) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistTv, [tvTable]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i3.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.TvModel>> getAiringToday({required int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getAiringToday, [], {#page: page}),
            returnValue: _i7.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]),
          )
          as _i7.Future<List<_i3.TvModel>>);

  @override
  _i7.Future<List<_i3.TvModel>> getOnTheAir({required int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAir, [], {#page: page}),
            returnValue: _i7.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]),
          )
          as _i7.Future<List<_i3.TvModel>>);

  @override
  _i7.Future<List<_i3.TvModel>> getPopularTv({required int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTv, [], {#page: page}),
            returnValue: _i7.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]),
          )
          as _i7.Future<List<_i3.TvModel>>);

  @override
  _i7.Future<List<_i3.TvModel>> getTopRatedTv({required int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTv, [], {#page: page}),
            returnValue: _i7.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]),
          )
          as _i7.Future<List<_i3.TvModel>>);

  @override
  _i7.Future<_i3.TvDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue: _i7.Future<_i3.TvDetailResponse>.value(
              _FakeTvDetailResponse_1(
                this,
                Invocation.method(#getTvDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.TvDetailResponse>);

  @override
  _i7.Future<List<_i3.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue: _i7.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]),
          )
          as _i7.Future<List<_i3.TvModel>>);

  @override
  _i7.Future<List<_i3.TvModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i7.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]),
          )
          as _i7.Future<List<_i3.TvModel>>);
}

/// A class which mocks [TvSeriesLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDatasource extends _i1.Mock
    implements _i3.TvSeriesLocalDatasource {
  MockTvSeriesLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> cacheAiringTodayTvSeries(List<_i3.TvSeriesTable>? tv) =>
      (super.noSuchMethod(
            Invocation.method(#cacheAiringTodayTvSeries, [tv]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheOnTheAirTvSeries(List<_i3.TvSeriesTable>? tv) =>
      (super.noSuchMethod(
            Invocation.method(#cacheOnTheAirTvSeries, [tv]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cachePopularTvSeries(List<_i3.TvSeriesTable>? tv) =>
      (super.noSuchMethod(
            Invocation.method(#cachePopularTvSeries, [tv]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheTopRatedTvSeries(List<_i3.TvSeriesTable>? tv) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTopRatedTvSeries, [tv]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheTvDetail(_i3.TvSeriesDetailTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTvDetail, [tv]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.TvSeriesTable>> getCachedAiringTodayTv() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAiringTodayTv, []),
            returnValue: _i7.Future<List<_i3.TvSeriesTable>>.value(
              <_i3.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i3.TvSeriesTable>>);

  @override
  _i7.Future<List<_i3.TvSeriesTable>> getCachedOnTheAirTv() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOnTheAirTv, []),
            returnValue: _i7.Future<List<_i3.TvSeriesTable>>.value(
              <_i3.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i3.TvSeriesTable>>);

  @override
  _i7.Future<List<_i3.TvSeriesTable>> getCachedPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPopularTv, []),
            returnValue: _i7.Future<List<_i3.TvSeriesTable>>.value(
              <_i3.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i3.TvSeriesTable>>);

  @override
  _i7.Future<List<_i3.TvSeriesTable>> getCachedTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTopRatedTv, []),
            returnValue: _i7.Future<List<_i3.TvSeriesTable>>.value(
              <_i3.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i3.TvSeriesTable>>);

  @override
  _i7.Future<_i3.TvSeriesDetailTable> getCachedTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTvDetail, [id]),
            returnValue: _i7.Future<_i3.TvSeriesDetailTable>.value(
              _FakeTvSeriesDetailTable_2(
                this,
                Invocation.method(#getCachedTvDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.TvSeriesDetailTable>);

  @override
  _i7.Future<String> insertWatchlist(_i3.TvSeriesTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tv]),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tv]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> removeWatchlist(_i3.TvSeriesTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tv]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i3.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i7.Future<_i3.TvSeriesTable?>.value(),
          )
          as _i7.Future<_i3.TvSeriesTable?>);

  @override
  _i7.Future<List<_i3.TvSeriesTable>> getWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTv, []),
            returnValue: _i7.Future<List<_i3.TvSeriesTable>>.value(
              <_i3.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i3.TvSeriesTable>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i3.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> getAiringToday({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAiringToday, [], {#page: page}),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#getAiringToday, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> getOnTheAir({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAir, [], {#page: page}),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#getOnTheAir, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> getPopularTv({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTv, [], {#page: page}),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#getPopularTv, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> getTopRatedTv({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTv, [], {#page: page}),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#getTopRatedTv, [], {#page: page}),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, _i3.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, _i3.TvDetail>>.value(
                  _FakeEither_3<_i6.Failure, _i3.TvDetail>(
                    this,
                    Invocation.method(#getTvDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, _i3.TvDetail>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> getTvRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#getTvRecommendations, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#searchTvSeries, [query]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> saveWatchlist(_i3.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tv]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, String>>.value(
              _FakeEither_3<_i6.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tv]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, String>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> removeWatchlist(
    _i3.TvDetail? tv,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, String>>.value(
              _FakeEither_3<_i6.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tv]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, String>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, bool>> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, bool>>.value(
              _FakeEither_3<_i6.Failure, bool>(
                this,
                Invocation.method(#isAddedToWatchlist, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, bool>>);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> getWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTv, []),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#getWatchlistTv, []),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);
}

/// A class which mocks [GetAiringTodayTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAiringTodayTv extends _i1.Mock implements _i3.GetAiringTodayTv {
  MockGetAiringTodayTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> execute(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [page]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#execute, [page]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);
}

/// A class which mocks [GetOnTheAirTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTv extends _i1.Mock implements _i3.GetOnTheAirTv {
  MockGetOnTheAirTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> execute(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [page]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#execute, [page]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);
}

/// A class which mocks [GetPopularTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTv extends _i1.Mock implements _i3.GetPopularTv {
  MockGetPopularTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> execute(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [page]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#execute, [page]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);
}

/// A class which mocks [SearchTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTvSeries extends _i1.Mock implements _i3.SearchTvSeries {
  MockSearchTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> execute(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i3.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, _i3.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, _i3.TvDetail>>.value(
                  _FakeEither_3<_i6.Failure, _i3.TvDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, _i3.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i3.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> execute(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);
}

/// A class which mocks [GetWatchListStatusTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusTv extends _i1.Mock
    implements _i3.GetWatchListStatusTv {
  MockGetWatchListStatusTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, bool>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, bool>>.value(
              _FakeEither_3<_i6.Failure, bool>(
                this,
                Invocation.method(#execute, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, bool>>);
}

/// A class which mocks [SaveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTv extends _i1.Mock implements _i3.SaveWatchlistTv {
  MockSaveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> execute(_i3.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tv]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, String>>.value(
              _FakeEither_3<_i6.Failure, String>(
                this,
                Invocation.method(#execute, [tv]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTv extends _i1.Mock implements _i3.RemoveWatchlistTv {
  MockRemoveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> execute(_i3.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tv]),
            returnValue: _i7.Future<_i4.Either<_i6.Failure, String>>.value(
              _FakeEither_3<_i6.Failure, String>(
                this,
                Invocation.method(#execute, [tv]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, String>>);
}

/// A class which mocks [GetTopRatedTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTv extends _i1.Mock implements _i3.GetTopRatedTv {
  MockGetTopRatedTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TvSeriesRepository);

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> execute(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [page]),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#execute, [page]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);
}

/// A class which mocks [GetWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTv extends _i1.Mock implements _i3.GetWatchlistTv {
  MockGetWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>.value(
                  _FakeEither_3<_i6.Failure, List<_i3.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i6.Failure, List<_i3.TvSeries>>>);
}

/// A class which mocks [SeeMoreOnTheAirTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeeMoreOnTheAirTvBloc extends _i1.Mock
    implements _i3.SeeMoreOnTheAirTvBloc {
  MockSeeMoreOnTheAirTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetOnTheAirTv get getOnTheAirTv =>
      (super.noSuchMethod(
            Invocation.getter(#getOnTheAirTv),
            returnValue: _FakeGetOnTheAirTv_5(
              this,
              Invocation.getter(#getOnTheAirTv),
            ),
          )
          as _i3.GetOnTheAirTv);

  @override
  _i3.SeeMoreOnTheAirTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSeeMoreOnTheAirTvState_6(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.SeeMoreOnTheAirTvState);

  @override
  _i7.Stream<_i3.SeeMoreOnTheAirTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.SeeMoreOnTheAirTvState>.empty(),
          )
          as _i7.Stream<_i3.SeeMoreOnTheAirTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i10.ScrollController? controller, _i11.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.SeeMoreOnTheAirTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.SeeMoreOnTheAirTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.SeeMoreOnTheAirTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.SeeMoreOnTheAirTvEvent>(
    _i12.EventHandler<E, _i3.SeeMoreOnTheAirTvState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.SeeMoreOnTheAirTvEvent, _i3.SeeMoreOnTheAirTvState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.SeeMoreOnTheAirTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SeeMorePopularTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeeMorePopularTvBloc extends _i1.Mock
    implements _i3.SeeMorePopularTvBloc {
  MockSeeMorePopularTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_7(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i3.GetPopularTv);

  @override
  _i3.SeeMorePopularTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSeeMorePopularTvState_8(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.SeeMorePopularTvState);

  @override
  _i7.Stream<_i3.SeeMorePopularTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.SeeMorePopularTvState>.empty(),
          )
          as _i7.Stream<_i3.SeeMorePopularTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i10.ScrollController? controller, _i11.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.SeeMorePopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.SeeMorePopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.SeeMorePopularTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.SeeMorePopularTvEvent>(
    _i12.EventHandler<E, _i3.SeeMorePopularTvState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.SeeMorePopularTvEvent, _i3.SeeMorePopularTvState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.SeeMorePopularTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSearchBloc extends _i1.Mock implements _i3.TvSearchBloc {
  MockTvSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SearchTvSeries get searchTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#searchTvSeries),
            returnValue: _FakeSearchTvSeries_9(
              this,
              Invocation.getter(#searchTvSeries),
            ),
          )
          as _i3.SearchTvSeries);

  @override
  _i3.TvSearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvSearchState_10(this, Invocation.getter(#state)),
          )
          as _i3.TvSearchState);

  @override
  _i7.Stream<_i3.TvSearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.TvSearchState>.empty(),
          )
          as _i7.Stream<_i3.TvSearchState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.TvSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.TvSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.TvSearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.TvSearchEvent>(
    _i12.EventHandler<E, _i3.TvSearchState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.TvSearchEvent, _i3.TvSearchState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.TvSearchState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SeeMoreTopRatedTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeeMoreTopRatedTvBloc extends _i1.Mock
    implements _i3.SeeMoreTopRatedTvBloc {
  MockSeeMoreTopRatedTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_11(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i3.GetTopRatedTv);

  @override
  _i3.SeeMoreTopRatedTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSeeMoreTopRatedTvState_12(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.SeeMoreTopRatedTvState);

  @override
  _i7.Stream<_i3.SeeMoreTopRatedTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.SeeMoreTopRatedTvState>.empty(),
          )
          as _i7.Stream<_i3.SeeMoreTopRatedTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onScroll(_i10.ScrollController? controller, _i11.VoidCallback? action) =>
      super.noSuchMethod(
        Invocation.method(#onScroll, [controller, action]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.SeeMoreTopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.SeeMoreTopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.SeeMoreTopRatedTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.SeeMoreTopRatedTvEvent>(
    _i12.EventHandler<E, _i3.SeeMoreTopRatedTvState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.SeeMoreTopRatedTvEvent, _i3.SeeMoreTopRatedTvState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.SeeMoreTopRatedTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailBloc extends _i1.Mock implements _i3.TvDetailBloc {
  MockTvDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetTvDetail get getTvDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTvDetail),
            returnValue: _FakeGetTvDetail_13(
              this,
              Invocation.getter(#getTvDetail),
            ),
          )
          as _i3.GetTvDetail);

  @override
  _i3.GetTvRecommendations get getTvRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTvRecommendations),
            returnValue: _FakeGetTvRecommendations_14(
              this,
              Invocation.getter(#getTvRecommendations),
            ),
          )
          as _i3.GetTvRecommendations);

  @override
  _i3.GetWatchListStatusTv get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatusTv_15(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i3.GetWatchListStatusTv);

  @override
  _i3.SaveWatchlistTv get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlistTv_16(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i3.SaveWatchlistTv);

  @override
  _i3.RemoveWatchlistTv get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlistTv_17(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i3.RemoveWatchlistTv);

  @override
  _i3.TvDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvDetailState_18(this, Invocation.getter(#state)),
          )
          as _i3.TvDetailState);

  @override
  _i7.Stream<_i3.TvDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.TvDetailState>.empty(),
          )
          as _i7.Stream<_i3.TvDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.TvDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.TvDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.TvDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.TvDetailEvent>(
    _i12.EventHandler<E, _i3.TvDetailState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.TvDetailEvent, _i3.TvDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.TvDetailState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AiringTodayTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiringTodayTvBloc extends _i1.Mock implements _i3.AiringTodayTvBloc {
  MockAiringTodayTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetAiringTodayTv get getAiringTodayTv =>
      (super.noSuchMethod(
            Invocation.getter(#getAiringTodayTv),
            returnValue: _FakeGetAiringTodayTv_19(
              this,
              Invocation.getter(#getAiringTodayTv),
            ),
          )
          as _i3.GetAiringTodayTv);

  @override
  _i3.AiringTodayTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAiringTodayTvState_20(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AiringTodayTvState);

  @override
  _i7.Stream<_i3.AiringTodayTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.AiringTodayTvState>.empty(),
          )
          as _i7.Stream<_i3.AiringTodayTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.AiringTodayTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.AiringTodayTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AiringTodayTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.AiringTodayTvEvent>(
    _i12.EventHandler<E, _i3.AiringTodayTvState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.AiringTodayTvEvent, _i3.AiringTodayTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.AiringTodayTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnTheAirTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvBloc extends _i1.Mock implements _i3.OnTheAirTvBloc {
  MockOnTheAirTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetOnTheAirTv get getOnTheAirTv =>
      (super.noSuchMethod(
            Invocation.getter(#getOnTheAirTv),
            returnValue: _FakeGetOnTheAirTv_5(
              this,
              Invocation.getter(#getOnTheAirTv),
            ),
          )
          as _i3.GetOnTheAirTv);

  @override
  _i3.OnTheAirTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOnTheAirTvState_21(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.OnTheAirTvState);

  @override
  _i7.Stream<_i3.OnTheAirTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.OnTheAirTvState>.empty(),
          )
          as _i7.Stream<_i3.OnTheAirTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.OnTheAirTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.OnTheAirTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.OnTheAirTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.OnTheAirTvEvent>(
    _i12.EventHandler<E, _i3.OnTheAirTvState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.OnTheAirTvEvent, _i3.OnTheAirTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.OnTheAirTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvBloc extends _i1.Mock implements _i3.PopularTvBloc {
  MockPopularTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_7(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i3.GetPopularTv);

  @override
  _i3.PopularTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularTvState_22(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.PopularTvState);

  @override
  _i7.Stream<_i3.PopularTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.PopularTvState>.empty(),
          )
          as _i7.Stream<_i3.PopularTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.PopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.PopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.PopularTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.PopularTvEvent>(
    _i12.EventHandler<E, _i3.PopularTvState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.PopularTvEvent, _i3.PopularTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.PopularTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvBloc extends _i1.Mock implements _i3.TopRatedTvBloc {
  MockTopRatedTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_11(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i3.GetTopRatedTv);

  @override
  _i3.TopRatedTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedTvState_23(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.TopRatedTvState);

  @override
  _i7.Stream<_i3.TopRatedTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.TopRatedTvState>.empty(),
          )
          as _i7.Stream<_i3.TopRatedTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.TopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.TopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.TopRatedTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.TopRatedTvEvent>(
    _i12.EventHandler<E, _i3.TopRatedTvState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.TopRatedTvEvent, _i3.TopRatedTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.TopRatedTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i10.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i10.Route<dynamic>? route, _i10.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i10.Route<dynamic>? newRoute,
    _i10.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i10.Route<dynamic>? topRoute,
    _i10.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i10.Route<dynamic>? route,
    _i10.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvBloc extends _i1.Mock implements _i3.WatchlistTvBloc {
  MockWatchlistTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetWatchlistTv get getWatchlistTv =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistTv),
            returnValue: _FakeGetWatchlistTv_24(
              this,
              Invocation.getter(#getWatchlistTv),
            ),
          )
          as _i3.GetWatchlistTv);

  @override
  _i3.WatchlistTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWatchlistTvState_25(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.WatchlistTvState);

  @override
  _i7.Stream<_i3.WatchlistTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.WatchlistTvState>.empty(),
          )
          as _i7.Stream<_i3.WatchlistTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.WatchlistTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.WatchlistTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.WatchlistTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.WatchlistTvEvent>(
    _i12.EventHandler<E, _i3.WatchlistTvState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i3.WatchlistTvEvent, _i3.WatchlistTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i12.Change<_i3.WatchlistTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i14.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i7.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
          )
          as _i7.Future<_i14.Uint8List>);

  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i7.Future<_i5.StreamedResponse>.value(
              _FakeStreamedResponse_27(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
